name: 'Kubernetes production deployment'
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Install kubectl
      uses: azure/setup-kubectl@v1

    - name: Decode kubeconfig
      run: echo $PRODUCTION_KUBERNETES_KUBECONFIG | base64 --decode > $GITHUB_WORKSPACE/deploy/kubeconfig.yml

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/deploy/kubeconfig.yml apply -f $GITHUB_WORKSPACE/deploy/manifests/deployment.yml

    # TODO add rollout status check
